export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export const SLACK_MISSING_CONFIGURATION_ERROR =
  'SLACK_MISSING_CONFIGURATION_ERROR';
export const SLACK_MISSING_POST_MESSAGE_SECRET_ERROR =
  'SLACK_MISSING_POST_MESSAGE_SECRET_ERROR';
export const SLACK_UNAUTHORIZED_POST_MESSAGE_ERROR =
  'Missing token or token invalid to post slack message';
export const SLACK_CHANNEL_NOT_FOUND_ERROR = 'SLACK_CHANNEL_NOT_FOUND_ERROR';
export const SLACK_ERROR = 'SLACK_ERROR';
