org: vjcspy
app: slack
service: chiaki-slack

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'ap-southeast-1'}
  bundle:
    linting: false
    excludeFiles: "**/*.test.ts"
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true
  environment:
    SLACK_BOT_TOKEN: ${param:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${param:SLACK_SIGNING_SECRET}
    SLACK_POST_MESSAGE_SECRET: ${param:SLACK_POST_MESSAGE_SECRET}

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 100
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline
